{
 "title": "Accelerator Metrics",
 "description": "AWS HyperPod Slurm Accelerator Metrics Dashboard",
 "tags": [
  "aws",
  "sagemaker",
  "hyperpod-slurm",
  "gpu",
  "version-1.0.0"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Node",
    "query": "label_values(DCGM_FI_DEV_GPU_TEMP, instance)"
   },
   { "name": "gpu", "query": "label_values(gpu)" },
   { "name": "hpc_job", "label": "Slurm Job Id", "query": "label_values(hpc_job)" },
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{instance=~\"${instance}\", gpu=~\"${gpu}\", hpc_job=~\"${hpc_job}\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Avg. Temp",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{instance=~\"${instance}\", gpu=~\"${gpu}\", hpc_job=~\"${hpc_job}\"})"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{instance=~\"${instance}\", gpu=~\"${gpu}\", hpc_job=~\"${hpc_job}\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Power Total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_POWER_USAGE{instance=~\"${instance}\", gpu=~\"${gpu}\", hpc_job=~\"${hpc_job}\"})"
    }
   ]
  },
  {
   "title": "GPU SM Clocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_SM_CLOCK{instance=~\"${instance}\", gpu=~\"${gpu}\", hpc_job=~\"${hpc_job}\"} * 1000000",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{instance=~\"${instance}\", gpu=~\"${gpu}\", hpc_job=~\"${hpc_job}\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Tensor Core Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{instance=~\"${instance}\", gpu=~\"${gpu}\", hpc_job=~\"${hpc_job}\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Framebuffer Mem Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{instance=~\"${instance}\", gpu=~\"${gpu}\", hpc_job=~\"${hpc_job}\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  }
 ]
}