{
 "title": "Network Metrics",
 "description": "AWS HyperPod Slurm EFA Metrics Dashboard",
 "tags": [
  "aws",
  "sagemaker",
  "hyperpod-slurm",
  "efa",
  "network",
  "version-1.0.0"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "job", "query": "efa_exporter" },
   {
    "name": "hostname",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\",nodename=~\"$hostname\"},instance)"
    }
   },
   { "name": "slurm_job_id", "label": "Slurm Job Id", "query": "label_values(slurm_job_id)" }
  ]
 },
 "panels": [
  {
   "title": "EFA Total Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(node_amazonefa_tx_bytes_total{instance=~\"$node\", slurm_job_id=~\"${slurm_job_id}\"}[$__rate_interval])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EFA rdma read/wrs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(node_amazonefa_rdma_read_wrs_total{instance=~\"$node\", slurm_job_id=~\"${slurm_job_id}\"}[$__rate_interval])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EFA Recv Bytes ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(node_amazonefa_recv_bytes_total{instance=~\"$node\", slurm_job_id=~\"${slurm_job_id}\"}[$__rate_interval])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EFA Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(node_amazonefa_tx_pkts_total{instance=~\"$node\", slurm_job_id=~\"${slurm_job_id}\"}[$__rate_interval])) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(sum by(instance) (rate(node_amazonefa_rx_drops{instance=~\"$node\", slurm_job_id=~\"${slurm_job_id}\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EFA RX Drops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(node_amazonefa_rx_drops_total{instance=~\"$node\", slurm_job_id=~\"${slurm_job_id}\"}[$__rate_interval])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read Write Errors with RDMA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(node_amazonefa_rdma_read_wr_err_total{instance=~\"$node\", slurm_job_id=~\"${slurm_job_id}\"}[$__rate_interval])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EFA Devices",
   "type": "table",
   "description": "Table listing EFA Device ID per node",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    { "expr": "node_amazonefa_info", "legendFormat": "__auto" }
   ]
  }
 ]
}