{
 "title": "Jobs",
 "description": "AWS HyperPod Slurm Job Dashboard",
 "tags": [
  "aws",
  "sagemaker",
  "hyperpod-slurm",
  "job",
  "version-1.0.0"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster_name",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(slurm_job_memory_rss_bytes, aws_sagemaker_hyperpod_cluster_name)"
    }
   },
   {
    "name": "cluster_id",
    "label": "Cluster ID",
    "query": {
     "query": "label_values(slurm_job_memory_rss_bytes{aws_sagemaker_hyperpod_cluster_name=~\"$cluster_name\"}, aws_sagemaker_hyperpod_cluster_id)"
    }
   },
   {
    "name": "slurm_job_id",
    "label": "Job ID",
    "query": {
     "query": "label_values(slurm_job_memory_rss_bytes{aws_sagemaker_hyperpod_cluster_name=~\"$cluster_name\", aws_sagemaker_hyperpod_cluster_id=~\"$cluster_id\"}, slurm_job_id)"
    }
   },
   {
    "name": "slurm_job_name",
    "label": "Job Name",
    "query": {
     "query": "label_values(slurm_job_memory_rss_bytes{aws_sagemaker_hyperpod_cluster_name=~\"$cluster_name\", aws_sagemaker_hyperpod_cluster_id=~\"$cluster_id\", slurm_job_id=~\"$slurm_job_id\"}, slurm_job_name)"
    }
   },
   {
    "name": "slurm_job_partition",
    "label": "Partition",
    "query": {
     "query": "label_values(slurm_job_memory_rss_bytes{aws_sagemaker_hyperpod_cluster_name=~\"$cluster_name\", aws_sagemaker_hyperpod_cluster_id=~\"$cluster_id\", slurm_job_id=~\"$slurm_job_id\", slurm_job_name=~\"$slurm_job_name\"}, slurm_job_partition)"
    }
   },
   {
    "name": "slurm_job_user",
    "label": "User",
    "query": {
     "query": "label_values(slurm_job_memory_rss_bytes{aws_sagemaker_hyperpod_cluster_name=~\"$cluster_name\", aws_sagemaker_hyperpod_cluster_id=~\"$cluster_id\", slurm_job_id=~\"$slurm_job_id\", slurm_job_name=~\"$slurm_job_name\", slurm_job_partition=~\"$slurm_job_partition\"}, slurm_job_user)"
    }
   },
   {
    "name": "slurm_job_account",
    "label": "Account",
    "query": {
     "query": "label_values(slurm_job_memory_rss_bytes{aws_sagemaker_hyperpod_cluster_name=~\"$cluster_name\", aws_sagemaker_hyperpod_cluster_id=~\"$cluster_id\", slurm_job_id=~\"$slurm_job_id\", slurm_job_name=~\"$slurm_job_name\", slurm_job_partition=~\"$slurm_job_partition\", slurm_job_user=~\"$slurm_job_user\"}, slurm_job_account)"
    }
   },
   {
    "name": "aggregated_by",
    "label": "Aggregate by:",
    "query": "Job ID : slurm_job_id, Job Name : slurm_job_name, User : slurm_job_user, Account : slurm_job_account, Partition : slurm_job_partition"
   },
   {
    "name": "hostname",
    "label": "Node Name",
    "query": {
     "query": "label_values(slurm_job_memory_rss_bytes{aws_sagemaker_hyperpod_cluster_name=~\"$cluster_name\", aws_sagemaker_hyperpod_cluster_id=~\"$cluster_id\", slurm_job_id=~\"$slurm_job_id\", slurm_job_name=~\"$slurm_job_name\", slurm_job_partition=~\"$slurm_job_partition\", slurm_job_user=~\"$slurm_job_user\", slurm_job_account=~\"$slurm_job_account\"}, hostname)"
    }
   },
   {
    "name": "instance",
    "label": "DCGM Node",
    "query": "label_values(DCGM_FI_DEV_GPU_TEMP, instance)"
   },
   { "name": "gpu", "query": "label_values(gpu)" },
   { "name": "hpc_job", "label": "DCGM Job", "query": "label_values(hpc_job)" },
   {
    "name": "slurm_job",
    "label": "NCCL Job Name",
    "query": "label_values(nccl_bus_bandwidth_gbs, slurm_job)"
   },
   {
    "name": "gpu_device_id",
    "label": "GPU Device",
    "query": "label_values(nccl_bus_bandwidth_gbs, gpu_device_id)"
   },
   {
    "name": "slurm_cluster_name",
    "label": "Slurm Cluster",
    "query": {
     "query": "label_values(slurm_job_memory_rss_bytes{aws_sagemaker_hyperpod_cluster_name=~\"$cluster_name\", aws_sagemaker_hyperpod_cluster_id=~\"$cluster_id\"}, slurm_cluster_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Job Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running Jobs Overview (Grouped by Job Name)",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "slurm_job_memory_rss_bytes{slurm_cluster_name=~\"${slurm_cluster_name}\", hostname=~\"${hostname}\", slurm_job_id=~\"${slurm_job_id}\", slurm_job_name=~\"${slurm_job_name}\", slurm_job_user=~\"${slurm_job_user}\", slurm_job_account=~\"${slurm_job_account}\", slurm_job_partition=~\"${slurm_job_partition}\", aws_sagemaker_hyperpod_cluster_name=~\"$cluster_name\", aws_sagemaker_hyperpod_cluster_id=~\"$cluster_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "slurm_job_thread_count{slurm_cluster_name=~\"${slurm_cluster_name}\", hostname=~\"${hostname}\", slurm_job_id=~\"${slurm_job_id}\", slurm_job_name=~\"${slurm_job_name}\", slurm_job_user=~\"${slurm_job_user}\", slurm_job_account=~\"${slurm_job_account}\", slurm_job_partition=~\"${slurm_job_partition}\", aws_sagemaker_hyperpod_cluster_name=~\"$cluster_name\", aws_sagemaker_hyperpod_cluster_id=~\"$cluster_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "slurm_job_process_count{slurm_cluster_name=~\"${slurm_cluster_name}\", hostname=~\"${hostname}\", slurm_job_id=~\"${slurm_job_id}\", slurm_job_name=~\"${slurm_job_name}\", slurm_job_user=~\"${slurm_job_user}\", slurm_job_account=~\"${slurm_job_account}\", slurm_job_partition=~\"${slurm_job_partition}\", aws_sagemaker_hyperpod_cluster_name=~\"$cluster_name\", aws_sagemaker_hyperpod_cluster_id=~\"$cluster_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(slurm_job_cpu_seconds_total{slurm_cluster_name=~\"${slurm_cluster_name}\", hostname=~\"${hostname}\", slurm_job_id=~\"${slurm_job_id}\", slurm_job_name=~\"${slurm_job_name}\", slurm_job_user=~\"${slurm_job_user}\", slurm_job_account=~\"${slurm_job_account}\", slurm_job_partition=~\"${slurm_job_partition}\", aws_sagemaker_hyperpod_cluster_name=~\"$cluster_name\", aws_sagemaker_hyperpod_cluster_id=~\"$cluster_id\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage: $slurm_job_id",
   "type": "timeseries",
   "description": "CPU usage for the selected job",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(slurm_job_cpu_seconds_total{slurm_cluster_name=~\"${slurm_cluster_name}\", hostname=~\"${hostname}\", slurm_job_id=~\"${slurm_job_id}\", slurm_job_name=~\"${slurm_job_name}\", slurm_job_user=~\"${slurm_job_user}\", slurm_job_account=~\"${slurm_job_account}\", slurm_job_partition=~\"${slurm_job_partition}\", aws_sagemaker_hyperpod_cluster_name=~\"$cluster_name\", aws_sagemaker_hyperpod_cluster_id=~\"$cluster_id\"}[$__rate_interval])) by ($aggregated_by)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage: $slurm_job_id",
   "type": "timeseries",
   "description": "Memory usage for the selected job",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(slurm_job_memory_rss_bytes{slurm_cluster_name=~\"${slurm_cluster_name}\", hostname=~\"${hostname}\", slurm_job_id=~\"${slurm_job_id}\", slurm_job_name=~\"${slurm_job_name}\", slurm_job_user=~\"${slurm_job_user}\", slurm_job_account=~\"${slurm_job_account}\", slurm_job_partition=~\"${slurm_job_partition}\", aws_sagemaker_hyperpod_cluster_name=~\"$cluster_name\", aws_sagemaker_hyperpod_cluster_id=~\"$cluster_id\"}) by ($aggregated_by)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Utilization: $slurm_job_id",
   "type": "timeseries",
   "description": "GPU utilization per job",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_UTIL{instance=~\"${hostname}\", hpc_job=~\"${slurm_job_id}\", aws_sagemaker_hyperpod_cluster_name=~\"$cluster_name\", aws_sagemaker_hyperpod_cluster_id=~\"$cluster_id\"}) by (gpu, hpc_job)",
     "legendFormat": "Job {{hpc_job}} GPU:{{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Memory: $slurm_job_id",
   "type": "timeseries",
   "description": "GPU memory usage per job",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_FB_USED{instance=~\"${hostname}\", hpc_job=~\"${slurm_job_id}\", aws_sagemaker_hyperpod_cluster_name=~\"$cluster_name\", aws_sagemaker_hyperpod_cluster_id=~\"$cluster_id\"}) by (hpc_job)",
     "legendFormat": "Job {{hpc_job}}"
    }
   ]
  },
  {
   "title": "Total Disk I/O (includes cache)",
   "type": "timeseries",
   "description": "Total bytes read and written including filesystem cache per job",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(rate(slurm_job_rchar_bytes_total{slurm_cluster_name=~\"${slurm_cluster_name}\", hostname=~\"${hostname}\", slurm_job_id=~\"${slurm_job_id}\", slurm_job_name=~\"${slurm_job_name}\", slurm_job_user=~\"${slurm_job_user}\", slurm_job_account=~\"${slurm_job_account}\", slurm_job_partition=~\"${slurm_job_partition}\", aws_sagemaker_hyperpod_cluster_name=~\"$cluster_name\", aws_sagemaker_hyperpod_cluster_id=~\"$cluster_id\"}[$__rate_interval])) by ($aggregated_by)",
     "legendFormat": "{{$aggregated_by}} Read"
    },
    {
     "expr": "avg(rate(slurm_job_wchar_bytes_total{slurm_cluster_name=~\"${slurm_cluster_name}\", hostname=~\"${hostname}\", slurm_job_id=~\"${slurm_job_id}\", slurm_job_name=~\"${slurm_job_name}\", slurm_job_user=~\"${slurm_job_user}\", slurm_job_account=~\"${slurm_job_account}\", slurm_job_partition=~\"${slurm_job_partition}\", aws_sagemaker_hyperpod_cluster_name=~\"$cluster_name\", aws_sagemaker_hyperpod_cluster_id=~\"$cluster_id\"}[$__rate_interval])) by ($aggregated_by)",
     "legendFormat": "{{$aggregated_by}} Write"
    }
   ]
  },
  {
   "title": "Accelerator Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_GPU_TEMP{instance=~\"${hostname}\", gpu=~\"${gpu}\", hpc_job=~\"${slurm_job_id}\", aws_sagemaker_hyperpod_cluster_name=~\"$cluster_name\", aws_sagemaker_hyperpod_cluster_id=~\"$cluster_id\"}",
       "legendFormat": "GPU {{gpu}}"
      }
     ]
    },
    {
     "title": "GPU Avg. Temp",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(DCGM_FI_DEV_GPU_TEMP{instance=~\"${hostname}\", gpu=~\"${gpu}\", hpc_job=~\"${slurm_job_id}\", aws_sagemaker_hyperpod_cluster_name=~\"$cluster_name\", aws_sagemaker_hyperpod_cluster_id=~\"$cluster_id\"})"
      }
     ]
    },
    {
     "title": "GPU Power Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_POWER_USAGE{instance=~\"${hostname}\", gpu=~\"${gpu}\", hpc_job=~\"${slurm_job_id}\", aws_sagemaker_hyperpod_cluster_name=~\"$cluster_name\", aws_sagemaker_hyperpod_cluster_id=~\"$cluster_id\"}",
       "legendFormat": "GPU {{gpu}}"
      }
     ]
    },
    {
     "title": "GPU Power Total",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(DCGM_FI_DEV_POWER_USAGE{instance=~\"${hostname}\", gpu=~\"${gpu}\", hpc_job=~\"${slurm_job_id}\", aws_sagemaker_hyperpod_cluster_name=~\"$cluster_name\", aws_sagemaker_hyperpod_cluster_id=~\"$cluster_id\"})"
      }
     ]
    },
    {
     "title": "GPU SM Clocks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "hertz" } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_SM_CLOCK{instance=~\"${hostname}\", gpu=~\"${gpu}\", hpc_job=~\"${slurm_job_id}\", aws_sagemaker_hyperpod_cluster_name=~\"$cluster_name\", aws_sagemaker_hyperpod_cluster_id=~\"$cluster_id\"} * 1000000",
       "legendFormat": "GPU {{gpu}}"
      }
     ]
    },
    {
     "title": "GPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_GPU_UTIL{instance=~\"${hostname}\", gpu=~\"${gpu}\", hpc_job=~\"${slurm_job_id}\", aws_sagemaker_hyperpod_cluster_name=~\"$cluster_name\", aws_sagemaker_hyperpod_cluster_id=~\"$cluster_id\"}",
       "legendFormat": "GPU {{gpu}}"
      }
     ]
    },
    {
     "title": "Tensor Core Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{instance=~\"${hostname}\", gpu=~\"${gpu}\", hpc_job=~\"${slurm_job_id}\", aws_sagemaker_hyperpod_cluster_name=~\"$cluster_name\", aws_sagemaker_hyperpod_cluster_id=~\"$cluster_id\"}",
       "legendFormat": "GPU {{gpu}}"
      }
     ]
    },
    {
     "title": "GPU Framebuffer Mem Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_FB_USED{instance=~\"${hostname}\", gpu=~\"${gpu}\", hpc_job=~\"${slurm_job_id}\", aws_sagemaker_hyperpod_cluster_name=~\"$cluster_name\", aws_sagemaker_hyperpod_cluster_id=~\"$cluster_id\"}",
       "legendFormat": "GPU {{gpu}}"
      }
     ]
    }
   ]
  },
  {
   "title": "NCCL Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "NCCL Algorithm Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "Gbits" } },
     "targets": [
      {
       "expr": "nccl_algorithm_bandwidth_gbs{instance=~\"${hostname}\", slurm_job_id=~\"${slurm_job_id}\", slurm_job=~\"${slurm_job_name}\", gpu_device_id=~\"${gpu_device_id}\", aws_sagemaker_hyperpod_cluster_name=~\"$cluster_name\", aws_sagemaker_hyperpod_cluster_id=~\"$cluster_id\"}",
       "legendFormat": "Job {{slurm_job_id}} {{collective}} gpu:{{gpu_device_id}} rank:{{rank}}"
      }
     ]
    },
    {
     "title": "NCCL Bus Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "Gbits" } },
     "targets": [
      {
       "expr": "nccl_bus_bandwidth_gbs{instance=~\"${hostname}\", slurm_job_id=~\"${slurm_job_id}\", slurm_job=~\"${slurm_job_name}\", gpu_device_id=~\"${gpu_device_id}\", aws_sagemaker_hyperpod_cluster_name=~\"$cluster_name\", aws_sagemaker_hyperpod_cluster_id=~\"$cluster_id\"}",
       "legendFormat": "Job {{slurm_job_id}} {{collective}} gpu:{{gpu_device_id}} rank:{{rank}}"
      }
     ]
    },
    {
     "title": "NCCL Collective Execution Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "nccl_collective_exec_time_microseconds{instance=~\"${hostname}\", slurm_job_id=~\"${slurm_job_id}\", slurm_job=~\"${slurm_job_name}\", gpu_device_id=~\"${gpu_device_id}\", aws_sagemaker_hyperpod_cluster_name=~\"$cluster_name\", aws_sagemaker_hyperpod_cluster_id=~\"$cluster_id\"}",
       "legendFormat": "Job {{slurm_job_id}} {{collective}} gpu:{{gpu_device_id}} rank:{{rank}}"
      }
     ]
    },
    {
     "title": "Avg Bus Bandwidth by Collective Type",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "Gbits" } },
     "targets": [
      {
       "expr": "avg(nccl_bus_bandwidth_gbs{instance=~\"${hostname}\", slurm_job_id=~\"${slurm_job_id}\", slurm_job=~\"${slurm_job_name}\", aws_sagemaker_hyperpod_cluster_name=~\"$cluster_name\", aws_sagemaker_hyperpod_cluster_id=~\"$cluster_id\"}) by (slurm_job_id, collective)",
       "legendFormat": "Job {{slurm_job_id}} {{collective}}"
      }
     ]
    },
    {
     "title": "Avg Execution Time by Collective Type",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "avg(nccl_collective_exec_time_microseconds{instance=~\"${hostname}\", slurm_job_id=~\"${slurm_job_id}\", slurm_job=~\"${slurm_job_name}\", aws_sagemaker_hyperpod_cluster_name=~\"$cluster_name\", aws_sagemaker_hyperpod_cluster_id=~\"$cluster_id\"}) by (slurm_job_id, collective)",
       "legendFormat": "Job {{slurm_job_id}} {{collective}}"
      }
     ]
    },
    {
     "title": "Avg Bus Bandwidth by GPU Device",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "Gbits" } },
     "targets": [
      {
       "expr": "avg(nccl_bus_bandwidth_gbs{instance=~\"${hostname}\", slurm_job_id=~\"${slurm_job_id}\", slurm_job=~\"${slurm_job_name}\", aws_sagemaker_hyperpod_cluster_name=~\"$cluster_name\", aws_sagemaker_hyperpod_cluster_id=~\"$cluster_id\"}) by (slurm_job_id, gpu_device_id)",
       "legendFormat": "Job {{slurm_job_id}} GPU {{gpu_device_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "More",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Physical Disk I/O",
     "type": "timeseries",
     "description": "Bytes read from and written to storage devices per job",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "avg(rate(slurm_job_read_bytes_total{slurm_cluster_name=~\"${slurm_cluster_name}\", hostname=~\"${hostname}\", slurm_job_id=~\"${slurm_job_id}\", slurm_job_name=~\"${slurm_job_name}\", slurm_job_user=~\"${slurm_job_user}\", slurm_job_account=~\"${slurm_job_account}\", slurm_job_partition=~\"${slurm_job_partition}\", aws_sagemaker_hyperpod_cluster_name=~\"$cluster_name\", aws_sagemaker_hyperpod_cluster_id=~\"$cluster_id\"}[$__rate_interval])) by ($aggregated_by)",
       "legendFormat": "{{$aggregated_by}} Read"
      },
      {
       "expr": "avg(rate(slurm_job_write_bytes_total{slurm_cluster_name=~\"${slurm_cluster_name}\", hostname=~\"${hostname}\", slurm_job_id=~\"${slurm_job_id}\", slurm_job_name=~\"${slurm_job_name}\", slurm_job_user=~\"${slurm_job_user}\", slurm_job_account=~\"${slurm_job_account}\", slurm_job_partition=~\"${slurm_job_partition}\", aws_sagemaker_hyperpod_cluster_name=~\"$cluster_name\", aws_sagemaker_hyperpod_cluster_id=~\"$cluster_id\"}[$__rate_interval])) by ($aggregated_by)",
       "legendFormat": "{{$aggregated_by}} Write"
      }
     ]
    },
    {
     "title": "Process Count",
     "type": "timeseries",
     "description": "Number of running processes per job",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(slurm_job_process_count{slurm_cluster_name=~\"${slurm_cluster_name}\", hostname=~\"${hostname}\", slurm_job_id=~\"${slurm_job_id}\", slurm_job_name=~\"${slurm_job_name}\", slurm_job_user=~\"${slurm_job_user}\", slurm_job_account=~\"${slurm_job_account}\", slurm_job_partition=~\"${slurm_job_partition}\", aws_sagemaker_hyperpod_cluster_name=~\"$cluster_name\", aws_sagemaker_hyperpod_cluster_id=~\"$cluster_id\"}) by ($aggregated_by)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Thread Count",
     "type": "timeseries",
     "description": "Number of threads across all job processes",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(slurm_job_thread_count{slurm_cluster_name=~\"${slurm_cluster_name}\", hostname=~\"${hostname}\", slurm_job_id=~\"${slurm_job_id}\", slurm_job_name=~\"${slurm_job_name}\", slurm_job_user=~\"${slurm_job_user}\", slurm_job_account=~\"${slurm_job_account}\", slurm_job_partition=~\"${slurm_job_partition}\", aws_sagemaker_hyperpod_cluster_name=~\"$cluster_name\", aws_sagemaker_hyperpod_cluster_id=~\"$cluster_id\"}) by ($aggregated_by)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Major Page Faults",
     "type": "timeseries",
     "description": "Major page faults per job",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "avg(rate(slurm_job_page_faults_major_total{slurm_cluster_name=~\"${slurm_cluster_name}\", hostname=~\"${hostname}\", slurm_job_id=~\"${slurm_job_id}\", slurm_job_name=~\"${slurm_job_name}\", slurm_job_user=~\"${slurm_job_user}\", slurm_job_account=~\"${slurm_job_account}\", slurm_job_partition=~\"${slurm_job_partition}\", aws_sagemaker_hyperpod_cluster_name=~\"$cluster_name\", aws_sagemaker_hyperpod_cluster_id=~\"$cluster_id\"}[$__rate_interval])) by ($aggregated_by)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}