"""
Unit tests for observability config generation in the Slurm observability config writer Lambda function
"""
import os
import sys
import unittest
import yaml
from unittest.mock import Mock

# Mock cfnresponse before importing lambda_function
sys.modules['cfnresponse'] = Mock()

# Add the lambda_function directory to the path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from lambda_function import build_config


class TestBuildConfig(unittest.TestCase):
    """Validate the schema and content of the observability config generated by build_config()."""

    ENV_VARS = {
        'AMP_REMOTE_WRITE_URL': 'https://aps-workspaces.us-west-2.amazonaws.com/workspaces/ws-abc123/api/v1/remote_write',
        'AMP_WORKSPACE_ARN': 'arn:aws:aps:us-west-2:123456789012:workspace/ws-abc123',
        'AMG_WORKSPACE_NAME': 'my-grafana-ws',
        'AMG_WORKSPACE_ARN': 'arn:aws:grafana:us-west-2:123456789012:/workspaces/g-xyz789',
        'NODE_METRIC_LEVEL': 'BASIC',
        'ACCELERATED_COMPUTE_METRIC_LEVEL': 'ADVANCED',
        'CLUSTER_METRIC_LEVEL': 'BASIC',
        'NETWORK_METRIC_LEVEL': 'DISABLED',
        'NCCL_METRIC_LEVEL': 'DISABLED',
        'JOB_METRIC_LEVEL': 'BASIC',
    }

    def setUp(self):
        for key, value in self.ENV_VARS.items():
            os.environ[key] = value

    def tearDown(self):
        for key in self.ENV_VARS:
            os.environ.pop(key, None)

    def test_top_level_schema(self):
        """Config must have apiVersion, kind, and spec at the top level."""
        config = build_config()
        self.assertEqual(config['apiVersion'], 'slurm.hyperpod.sagemaker.amazonaws.com/v1alpha1')
        self.assertEqual(config['kind'], 'ObservabilityConfig')
        self.assertIn('spec', config)

    def test_spec_enabled(self):
        """spec.enabled must be True."""
        config = build_config()
        self.assertTrue(config['spec']['enabled'])

    def test_amp_workspace_uses_remote_write_url(self):
        """prometheusEndpoint must be the full remote write URL (with /api/v1/remote_write)."""
        config = build_config()
        endpoint = config['spec']['ampWorkspace']['prometheusEndpoint']
        self.assertTrue(endpoint.endswith('/api/v1/remote_write'),
                        f"Expected remote write URL, got: {endpoint}")
        self.assertEqual(endpoint, self.ENV_VARS['AMP_REMOTE_WRITE_URL'])

    def test_amp_workspace_arn(self):
        config = build_config()
        self.assertEqual(config['spec']['ampWorkspace']['arn'], self.ENV_VARS['AMP_WORKSPACE_ARN'])

    def test_amg_workspace(self):
        config = build_config()
        amg = config['spec']['amgWorkspace']
        self.assertEqual(amg['workspaceName'], self.ENV_VARS['AMG_WORKSPACE_NAME'])
        self.assertEqual(amg['arn'], self.ENV_VARS['AMG_WORKSPACE_ARN'])

    def test_poller_defaults(self):
        config = build_config()
        poller = config['spec']['poller']
        self.assertTrue(poller['enabled'])
        self.assertEqual(poller['pollingIntervalSeconds'], 300)

    def test_metrics_provider_has_all_categories(self):
        """metricsProvider must contain all 6 metric categories."""
        config = build_config()
        metrics = config['spec']['metricsProvider']
        expected_keys = [
            'nodeMetrics', 'acceleratedComputeMetrics', 'clusterMetrics',
            'networkMetrics', 'ncclMetrics', 'jobMetrics',
        ]
        for key in expected_keys:
            self.assertIn(key, metrics, f"Missing metric category: {key}")

    def test_metric_levels_match_env(self):
        """Each metric category's level must match the corresponding env var."""
        config = build_config()
        metrics = config['spec']['metricsProvider']
        self.assertEqual(metrics['nodeMetrics']['level'], 'BASIC')
        self.assertEqual(metrics['acceleratedComputeMetrics']['level'], 'ADVANCED')
        self.assertEqual(metrics['clusterMetrics']['level'], 'BASIC')
        self.assertEqual(metrics['networkMetrics']['level'], 'DISABLED')
        self.assertEqual(metrics['ncclMetrics']['level'], 'DISABLED')
        self.assertEqual(metrics['jobMetrics']['level'], 'BASIC')

    def test_metric_scrape_intervals(self):
        """All metric categories must have scrapeIntervalSeconds set to 30."""
        config = build_config()
        metrics = config['spec']['metricsProvider']
        for key, section in metrics.items():
            self.assertEqual(section['scrapeIntervalSeconds'], 30,
                             f"{key} scrapeIntervalSeconds should be 30")

    def test_valid_metric_levels(self):
        """All metric levels must be one of BASIC, ADVANCED, or DISABLED."""
        config = build_config()
        valid_levels = {'BASIC', 'ADVANCED', 'DISABLED'}
        metrics = config['spec']['metricsProvider']
        for key, section in metrics.items():
            self.assertIn(section['level'], valid_levels,
                          f"{key} has invalid level: {section['level']}")

    def test_config_serializes_to_valid_yaml(self):
        """The config must serialize to valid YAML and round-trip cleanly."""
        config = build_config()
        yaml_str = yaml.dump(config, default_flow_style=False, sort_keys=False)
        parsed = yaml.safe_load(yaml_str)
        self.assertEqual(parsed['spec']['ampWorkspace']['prometheusEndpoint'],
                         self.ENV_VARS['AMP_REMOTE_WRITE_URL'])

    def test_missing_amp_remote_write_url_raises(self):
        """build_config must fail if AMP_REMOTE_WRITE_URL is not set."""
        del os.environ['AMP_REMOTE_WRITE_URL']
        with self.assertRaises(KeyError):
            build_config()

    def test_missing_amp_workspace_arn_raises(self):
        """build_config must fail if AMP_WORKSPACE_ARN is not set."""
        del os.environ['AMP_WORKSPACE_ARN']
        with self.assertRaises(KeyError):
            build_config()

    def test_missing_amg_workspace_name_raises(self):
        """build_config must fail if AMG_WORKSPACE_NAME is not set."""
        del os.environ['AMG_WORKSPACE_NAME']
        with self.assertRaises(KeyError):
            build_config()

    def test_missing_amg_workspace_arn_raises(self):
        """build_config must fail if AMG_WORKSPACE_ARN is not set."""
        del os.environ['AMG_WORKSPACE_ARN']
        with self.assertRaises(KeyError):
            build_config()

    def test_missing_node_metric_level_raises(self):
        """build_config must fail if NODE_METRIC_LEVEL is not set."""
        del os.environ['NODE_METRIC_LEVEL']
        with self.assertRaises(KeyError):
            build_config()

    def test_missing_cluster_metric_level_raises(self):
        """build_config must fail if CLUSTER_METRIC_LEVEL is not set."""
        del os.environ['CLUSTER_METRIC_LEVEL']
        with self.assertRaises(KeyError):
            build_config()

    def test_missing_job_metric_level_raises(self):
        """build_config must fail if JOB_METRIC_LEVEL is not set."""
        del os.environ['JOB_METRIC_LEVEL']
        with self.assertRaises(KeyError):
            build_config()


if __name__ == '__main__':
    unittest.main()
