{
 "title": "Inference",
 "description": "HyperPod Inference Dashboard",
 "tags": [
  "aws",
  "sagemaker",
  "hyperpod",
  "metrics",
  "model"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster_name",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(kube_node_info,cluster_name)"
    }
   },
   {
    "name": "cluster_id",
    "label": "Cluster ID",
    "query": {
     "query": "label_values(kube_node_info{cluster_name=\"$cluster_name\"},cluster_id)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(model_invocations_total{resource_type=~\"$resourceType\"}, namespace)"
   },
   {
    "name": "resourceType",
    "label": "Deployment Type",
    "query": "label_values(model_invocations_total, resource_type)"
   },
   {
    "name": "resource",
    "label": "Deployment Name",
    "query": "label_values(model_invocations_total{resource_type=~\"$resourceType\", namespace=~\"$namespace\"}, resource_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "List of Active Deployments",
   "type": "table",
   "description": "List of all deployments on your SageMaker HyperPod cluster",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "group by (resource_name, resource_type, model_name, model_version, instance_type, model_container_type, model_container_image) (model_invocations_total{cluster_id=\"$cluster_id\",resource_type=~\"$resourceType\", namespace=~\"$namespace\", resource_name=~\"$resource\"})"
    },
    {
     "expr": "count by (resource_name) (count by (resource_name, pod_name) (max_over_time(model_invocations_total{cluster_id=\"$cluster_id\",resource_type=~\"$resourceType\", namespace=~\"$namespace\", resource_name=~\"$resource\"}[5m])))"
    },
    {
     "expr": "count by (resource_name) (count by (resource_name, node_name) (max_over_time(model_invocations_total{cluster_id=\"$cluster_id\",resource_type=~\"$resourceType\", namespace=~\"$namespace\", resource_name=~\"$resource\"}[5m])))"
    }
   ]
  },
  {
   "title": "Incoming Request Rate per Deployment",
   "type": "timeseries",
   "description": "Incoming requests per deployment per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(model_invocations_total{cluster_id=\"$cluster_id\",resource_type=~\"$resourceType\", namespace=~\"$namespace\", resource_name=~\"$resource\", method=\"POST\", uri=\"/invocations\"}[5m])",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Percentage of Successful Requests",
   "type": "timeseries",
   "description": "Total number of incoming requests successfully served by the model over total number of incoming requests",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - ((sum by (resource_name) (rate(model_errors_total{cluster_id=\"$cluster_id\",resource_type=~\"$resourceType\", namespace=~\"$namespace\", resource_name=~\"$resource\", method=\"POST\", uri=\"/invocations\"}[5m])) or vector(0)) / sum by (resource_name) (rate(model_invocations_total{cluster_id=\"$cluster_id\",resource_type=~\"$resourceType\", namespace=~\"$namespace\", resource_name=~\"$resource\", method=\"POST\", uri=\"/invocations\"}[5m])))) * 100",
     "legendFormat": "{{resource_name}} Success Rate"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Successful Requests vs Failed Requests",
   "type": "timeseries",
   "description": "Number of requests that were successfully processed by the model vs number of requests that failed to get a response from the model",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (resource_name) (increase(model_latency_milliseconds_count{cluster_id=\"$cluster_id\",resource_type=~\"$resourceType\", namespace=~\"$namespace\", resource_name=~\"$resource\", method=\"POST\", uri=\"/invocations\", status=~\"2.*\"}[5m]))",
     "legendFormat": "{{resource_name}} Successful"
    },
    {
     "expr": "sum by (resource_name) (increase(model_errors_total{cluster_id=\"$cluster_id\",resource_type=~\"$resourceType\", namespace=~\"$namespace\", resource_name=~\"$resource\", method=\"POST\", uri=\"/invocations\"}[5m]))",
     "legendFormat": "{{resource_name}} Failed"
    }
   ]
  },
  {
   "title": "Count of Failed Requests per Error Code",
   "type": "timeseries",
   "description": "Number of incoming requests that failed to get a successful response from the deployed model split by error codes.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(model_errors_total{cluster_id=\"$cluster_id\",resource_type=~\"$resourceType\", namespace=~\"$namespace\", resource_name=~\"$resource\", method=\"POST\", uri=\"/invocations\"}[5m])",
     "legendFormat": "{{resource_name}} - {{status}}"
    }
   ]
  },
  {
   "title": "Latency of Successful Requests",
   "type": "timeseries",
   "description": "Time it takes for an incoming request to get a successful response from the model",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(model_latency_milliseconds_bucket{cluster_id=\"$cluster_id\",resource_type=~\"$resourceType\", namespace=~\"$namespace\", resource_name=~\"$resource\", method=\"POST\", uri=\"/invocations\", status=~\"2.*\"}[5m])) by (resource_name, le))",
     "legendFormat": "{{resource_name}} p90"
    }
   ]
  },
  {
   "title": "Time To First Byte (TTFB)",
   "type": "timeseries",
   "description": "Time it takes for the model to send the first byte of response to an incoming request",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(model_ttfb_milliseconds_bucket{cluster_id=\"$cluster_id\",resource_type=~\"$resourceType\", namespace=~\"$namespace\", resource_name=~\"$resource\", method=\"POST\", uri=\"/invocations\", status=~\"2.*\"}[5m])) by (resource_name, le))",
     "legendFormat": "{{resource_name}} TTFB p90"
    }
   ]
  },
  {
   "title": "TTFB to Total Latency Ratio",
   "type": "timeseries",
   "description": "Helps to identify if the latency of a response by the model was mainly due to delays in initial processing (first byte)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(model_ttfb_milliseconds_bucket{cluster_id=\"$cluster_id\",resource_type=~\"$resourceType\", namespace=~\"$namespace\", resource_name=~\"$resource\", method=\"POST\", uri=\"/invocations\", status=~\"2.*\"}[5m])) by (resource_name, le)) / histogram_quantile(0.90, sum(rate(model_latency_milliseconds_bucket{cluster_id=\"$cluster_id\",resource_type=~\"$resourceType\", namespace=~\"$namespace\", resource_name=~\"$resource\", method=\"POST\", uri=\"/invocations\", status=~\"2.*\"}[5m])) by (resource_name, le))",
     "legendFormat": "{{resource_name}} TTFB/Total Ratio (p90)"
    }
   ]
  },
  {
   "title": "Total Concurrent Requests",
   "type": "timeseries",
   "description": "Total number of concurrent requests being processed by each deployment",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (resource_name) (model_concurrent_requests{cluster_id=\"$cluster_id\",resource_type=~\"$resourceType\", namespace=~\"$namespace\", resource_name=~\"$resource\", method=\"POST\", uri=\"/invocations\"})",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Infrastructure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Infrastructure Allocation (Pods & Nodes)",
     "type": "timeseries",
     "description": "Total infrastructure allocation - pods and nodes per deployment",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by (resource_name) (count by (resource_name, pod_name) (max_over_time(model_invocations_total{cluster_id=\"$cluster_id\",resource_type=~\"$resourceType\", namespace=~\"$namespace\", resource_name=~\"$resource\"}[5m])))",
       "legendFormat": "{{resource_name}} Total Pods"
      },
      {
       "expr": "count by (resource_name) (count by (resource_name, node_name) (max_over_time(model_invocations_total{cluster_id=\"$cluster_id\",resource_type=~\"$resourceType\", namespace=~\"$namespace\", resource_name=~\"$resource\"}[5m])))",
       "legendFormat": "{{resource_name}} Total Nodes"
      }
     ]
    },
    {
     "title": "Active Pods (Receiving Traffic)",
     "type": "timeseries",
     "description": "Active pods currently receiving incoming requests  per deployment",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by (resource_name) (count by (resource_name, pod_name) (rate(model_invocations_total{cluster_id=\"$cluster_id\",resource_type=~\"$resourceType\", namespace=~\"$namespace\", resource_name=~\"$resource\"}[5m]) > 0))",
       "legendFormat": "{{resource_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "TGI (Text Generation Inference) Token Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Time to First Token (TTFT)",
     "type": "timeseries",
     "description": "Time it takes for the model to create the first token for an incoming request",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "(histogram_quantile(0.90, sum by (resource_name, le) (rate(tgi_request_queue_duration_bucket{cluster_id=\"$cluster_id\",resource_type=~\"$resourceType\", namespace=~\"$namespace\", resource_name=~\"$resource\"}[5m]))) + histogram_quantile(0.90, sum by (resource_name, le) (rate(tgi_batch_inference_duration_bucket{cluster_id=\"$cluster_id\",method=\"prefill\", resource_type=~\"$resourceType\", namespace=~\"$namespace\", resource_name=~\"$resource\"}[5m])))) * 1000",
       "legendFormat": "{{resource_name}} TTFT p90"
      }
     ]
    },
    {
     "title": "Inter-Token Latency (Decode)",
     "type": "timeseries",
     "description": "Average time it takes for the model to generate two consecutive tokens across all tokens. Determines streaming responsiveness for TGI deployments",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum by (resource_name, le) (rate(tgi_batch_forward_duration_bucket{cluster_id=\"$cluster_id\",method=\"decode\", resource_type=~\"$resourceType\", namespace=~\"$namespace\", resource_name=~\"$resource\"}[5m]))) * 1000",
       "legendFormat": "{{resource_name}} Inter-Token p90"
      }
     ]
    },
    {
     "title": "Token Throughput",
     "type": "timeseries",
     "description": "Number of tokens generated per second by the model. Represents efficiency and capacity indicator for TGI deployments",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "tok/s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum by (resource_name, le) (rate(tgi_request_generated_tokens_bucket{cluster_id=\"$cluster_id\",resource_type=~\"$resourceType\", namespace=~\"$namespace\", resource_name=~\"$resource\"}[5m])))",
       "legendFormat": "{{resource_name}} Token Throughput p90"
      }
     ]
    },
    {
     "title": "Mean Time Per Token",
     "type": "timeseries",
     "description": "Average time it takes for the model to generate every token required to respond to an incoming request",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum by (resource_name, le) (rate(tgi_request_mean_time_per_token_duration_bucket{cluster_id=\"$cluster_id\",resource_type=~\"$resourceType\", namespace=~\"$namespace\", resource_name=~\"$resource\"}[5m])))",
       "legendFormat": "{{resource_name}} Mean Time Per Token p90"
      }
     ]
    }
   ]
  },
  {
   "title": "LMI (Large Model Inference) Token Metrics - aggregated over every 10 requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Mean Token Latency",
     "type": "timeseries",
     "description": "Average time it takes to generate a token per request over last 10 consecutive requests",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "TokenLatency_p90{cluster_id=\"$cluster_id\",resource_type=~\"$resourceType\", namespace=~\"$namespace\", resource_name=~\"$resource\"}",
       "legendFormat": "{{resource_name}} Token Latency p90"
      }
     ]
    },
    {
     "title": "Mean Token Throughput",
     "type": "timeseries",
     "description": "Average number of tokens per second per request over last 10 consecutive requests",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "tok/s" } },
     "targets": [
      {
       "expr": "TokenThroughput_p90{cluster_id=\"$cluster_id\",resource_type=~\"$resourceType\", namespace=~\"$namespace\", resource_name=~\"$resource\"}",
       "legendFormat": "{{resource_name}} Token Throughput p90"
      }
     ]
    },
    {
     "title": "Mean Output Tokens per Request",
     "type": "timeseries",
     "description": "Average total output tokens generated per request over last 10 consecutive requests",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "OutputTokens_p90{cluster_id=\"$cluster_id\",resource_type=~\"$resourceType\", namespace=~\"$namespace\", resource_name=~\"$resource\"}",
       "legendFormat": "{{resource_name}} Output Tokens p90"
      }
     ]
    },
    {
     "title": "Rolling Batch Size",
     "type": "timeseries",
     "description": "Average rolling batch size — indicating concurrency during batching — calculated per request over the last 10 consecutive requests",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "RollingBatchSize_p90{cluster_id=\"$cluster_id\",resource_type=~\"$resourceType\", namespace=~\"$namespace\", resource_name=~\"$resource\"}",
       "legendFormat": "{{resource_name}} Rolling Batch Size p90"
      }
     ]
    }
   ]
  },
  { "title": "Help", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 47 },
   "options": {
    "content": "To enable additional metrics or troubleshoot issues, refer to the Amazon SageMaker HyperPod observability user guide: https://docs.aws.amazon.com/sagemaker/latest/dg/sagemaker-hyperpod-eks-cluster-observability-cluster.html"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Feedback?",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 50 },
   "options": {
    "content": "Tell us how we can improve your Amazon SageMaker HyperPod observability experience by reporting bugs or submitting feature requests here\nhttps://github.com/aws/amazon-sagemaker-feedback/issues"
   }
  }
 ]
}