{
 "title": "Tasks",
 "tags": [
  "hyperpod",
  "task",
  "aws",
  "sagemaker",
  "pod",
  "version-1.1.1"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster_name",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(kube_node_info,cluster_name)"
    }
   },
   {
    "name": "cluster_id",
    "label": "Cluster ID",
    "query": {
     "query": "label_values(kube_node_info{cluster_name=\"$cluster_name\"},cluster_id)"
    }
   },
   {
    "name": "aggregated_by",
    "label": "Aggregate by:",
    "query": "Task Pod : pod, Namespace : namespace,Task Name : created_by_name"
   },
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "created_by_kind",
    "label": "Task Type",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, created_by_kind)"
    }
   },
   {
    "name": "created_by_name",
    "label": "Task Name",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\", created_by_kind=~\"$created_by_kind\"}, created_by_name)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\", created_by_kind=~\"$created_by_kind\", created_by_name=~\"$created_by_name\"}, pod)"
    }
   },
   {
    "name": "gpu",
    "label": "GPU ID",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_UTIL, gpu)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Resource usage per Task (Grouped by Parent Task)",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{cluster_id=\"$cluster_id\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\"}[5m]) * on(pod, namespace) group_left(created_by_name, created_by_kind, node) group by(pod, namespace, created_by_name, created_by_kind, node) (label_replace(kube_pod_info{cluster_id=\"$cluster_id\", namespace=~\"$namespace\", created_by_kind=~\"$created_by_kind\", created_by_name=~\"$created_by_name\", pod=~\"$pod\"}, \"GPU_I_PROFILE\", \"mig-$1\", \"GPU_I_PROFILE\", \"(.+)\"))",
     "legendFormat": "__auto"
    },
    {
     "expr": "container_memory_usage_bytes{cluster_id=\"$cluster_id\",namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\"} * on(pod, namespace) group_left(created_by_name, created_by_kind, node) label_replace(kube_pod_info{cluster_id=\"$cluster_id\",namespace=~\"$namespace\", created_by_kind=~\"$created_by_kind\", created_by_name=~\"$created_by_name\", pod=~\"$pod\"}, \"GPU_I_PROFILE\", \"mig-$1\", \"GPU_I_PROFILE\", \"(.+)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(DCGM_FI_DEV_GPU_UTIL{cluster_id=\"$cluster_id\",namespace=~\"$namespace\", pod=~\"$pod\"} * on(pod, namespace) group_left(created_by_name, created_by_kind, node) kube_pod_info{cluster_id=\"$cluster_id\",namespace=~\"$namespace\", created_by_kind=~\"$created_by_kind\", created_by_name=~\"$created_by_name\", pod=~\"$pod\"}, \"GPU_I_PROFILE\", \"mig-$1\", \"GPU_I_PROFILE\", \"(.+)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(DCGM_FI_DEV_FB_USED{cluster_id=\"$cluster_id\",namespace=~\"$namespace\", pod=~\"$pod\"} * on(pod, namespace) group_left(created_by_name, created_by_kind, node) group by(pod, namespace, created_by_name, created_by_kind, node) (kube_pod_info{cluster_id=\"$cluster_id\",namespace=~\"$namespace\", created_by_kind=~\"$created_by_kind\", created_by_name=~\"$created_by_name\", pod=~\"$pod\"}), \"GPU_I_PROFILE\", \"mig-$1\", \"GPU_I_PROFILE\", \"(.+)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(avg(DCGM_FI_PROF_GR_ENGINE_ACTIVE{cluster_id=\"$cluster_id\", namespace=~\"$namespace\", pod=~\"$pod\"} * on(pod, namespace) group_left(created_by_name, created_by_kind) group by(pod, namespace, created_by_name, created_by_kind) (kube_pod_info{cluster_id=\"$cluster_id\", namespace=~\"$namespace\", created_by_kind=~\"$created_by_kind\", created_by_name=~\"$created_by_name\", pod=~\"$pod\"})) by (pod, GPU_I_PROFILE, GPU_I_ID) * 100, \"GPU_I_PROFILE\", \"mig-$1\", \"GPU_I_PROFILE\", \"(.+)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage: $pod",
   "type": "timeseries",
   "description": "CPU usage for the selected pod",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "\navg(rate(container_cpu_usage_seconds_total{cluster_id=\"$cluster_id\",namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\"}[5m]) * on(pod) group_left(created_by_name, created_by_kind) group by(pod, created_by_name, created_by_kind) (kube_pod_info{cluster_id=\"$cluster_id\",namespace=~\"$namespace\", created_by_kind=~\"$created_by_kind\", created_by_name=~\"$created_by_name\", pod=~\"$pod\", host_ip!=\"\", pod_ip!=\"\"})) by ($aggregated_by) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage: $pod",
   "type": "timeseries",
   "description": "Memory usage for the selected pod",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{cluster_id=\"$cluster_id\",namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\"} * on(pod, namespace) group_left(created_by_name, created_by_kind) group by(pod, namespace, created_by_name, created_by_kind) (kube_pod_info{cluster_id=\"$cluster_id\",namespace=~\"$namespace\", created_by_kind=~\"$created_by_kind\", created_by_name=~\"$created_by_name\", pod=~\"$pod\", host_ip!=\"\", pod_ip!=\"\"})) by ($aggregated_by)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Utilization: $pod",
   "type": "timeseries",
   "description": "GPU utilization by pod",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_UTIL{cluster_id=\"$cluster_id\",namespace=~\"$namespace\", pod=~\"$pod\", gpu=~\"$gpu\"} * on(pod, namespace) group_left(created_by_name, created_by_kind) kube_pod_info{cluster_id=\"$cluster_id\",namespace=~\"$namespace\", created_by_kind=~\"$created_by_kind\", created_by_name=~\"$created_by_name\", pod=~\"$pod\", host_ip!=\"\", pod_ip!=\"\"}) by (gpu,$aggregated_by)",
     "legendFormat": "{{$aggregated_by}}"
    }
   ]
  },
  {
   "title": "GPU Memory: $pod",
   "type": "timeseries",
   "description": "GPU memory usage by pod",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_FB_USED{cluster_id=\"$cluster_id\",namespace=~\"$namespace\", pod=~\"$pod\", gpu=~\"$gpu\"} * on(pod) group_left(created_by_name, created_by_kind) group by(pod, created_by_name, created_by_kind) (kube_pod_info{cluster_id=\"$cluster_id\",namespace=~\"$namespace\", created_by_kind=~\"$created_by_kind\", created_by_name=~\"$created_by_name\", pod=~\"$pod\", host_ip!=\"\", pod_ip!=\"\"})) by ($aggregated_by)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Partition Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(label_replace(avg(DCGM_FI_PROF_GR_ENGINE_ACTIVE{cluster_id=\"$cluster_id\",namespace=~\"$namespace\", pod=~\"$pod\", gpu=~\"$gpu\", GPU_I_PROFILE!=\"\"} * on(pod, namespace) group_left(created_by_name, created_by_kind) group by(pod, namespace, created_by_name, created_by_kind) (kube_pod_info{cluster_id=\"$cluster_id\",namespace=~\"$namespace\", created_by_kind=~\"$created_by_kind\", created_by_name=~\"$created_by_name\", pod=~\"$pod\", host_ip!=\"\", pod_ip!=\"\"})) by (GPU_I_ID, Hostname, gpu, GPU_I_PROFILE, pod, created_by_name, namespace), \"partition_display\", \"mig-$1\", \"GPU_I_PROFILE\", \"(.*)\")) or (label_replace(avg(DCGM_FI_PROF_GR_ENGINE_ACTIVE{cluster_id=\"$cluster_id\",namespace=~\"$namespace\", pod=~\"$pod\", gpu=~\"$gpu\", GPU_I_PROFILE=\"\"} * on(pod, namespace) group_left(created_by_name, created_by_kind) group by(pod, namespace, created_by_name, created_by_kind) (kube_pod_info{cluster_id=\"$cluster_id\",namespace=~\"$namespace\", created_by_kind=~\"$created_by_kind\", created_by_name=~\"$created_by_name\", pod=~\"$pod\", host_ip!=\"\", pod_ip!=\"\"})) by (GPU_I_ID, Hostname, gpu, GPU_I_PROFILE, pod, created_by_name, namespace), \"partition_display\", \"\", \"GPU_I_PROFILE\", \"\"))",
     "legendFormat": "{{$aggregated_by}} GPU:{{gpu}}  GPU Partition Type:{{partition_display}}  ID:{{GPU_I_ID}}"
    }
   ]
  },
  { "title": "Help", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 27 },
   "options": {
    "content": "To enable additional metrics or troubleshoot issues, refer to the Amazon SageMaker HyperPod observability user guide: https://docs.aws.amazon.com/sagemaker/latest/dg/sagemaker-hyperpod-eks-cluster-observability-cluster.html"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Feedback?",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 30 },
   "options": {
    "content": "Tell us how we can improve your Amazon SageMaker HyperPod observability experience by reporting bugs or submitting feature requests here\nhttps://github.com/aws/amazon-sagemaker-feedback/issues"
   }
  }
 ]
}