Description: EKS Cluster Stack
Parameters:
  ResourceNamePrefix:
    Type: String
    Default: sagemaker-hyperpod-eks
    Description: Prefix to be used for all resources created by this template.
  VpcId:
    Type: String
    Default: vpc-1234567890abcdef0
    Description: The ID of the VPC you wish to use if you do not want to create a new VPC.
  KubernetesVersion:
    Type: String
    Default: '1.31'
    Description: The Kubernetes version to use for the EKS cluster.
  EKSClusterName:
    Type: String
    Default: eks
    Description: The name of the newly created EKS cluster you wish to use.
  EksPrivateSubnetIds:
    Type: CommaDelimitedList
    Default: subnet-1234567890abcdef0,subnet-1234567890abcdef0
    Description: Comma-delimited list of private subnet IDs for the EKS cluster
  SecurityGroupIds:
    Type: CommaDelimitedList
    Default: sg-1234567890abcdef0
    Description: The Id of your cluster security group.
Resources:
  ClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
      Path: /
      RoleName:
        Fn::Sub: ${ResourceNamePrefix}-role
      Tags:
        - Key: aws-sagemaker-hyperpod-prerequiste
          Value:
            Fn::Sub: ${ResourceNamePrefix}-role
    Metadata:
      aws:cdk:path: EksCfnTemplate/ClusterRole
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      AccessConfig:
        AuthenticationMode: API_AND_CONFIG_MAP
      Logging:
        ClusterLogging:
          EnabledTypes:
            - Type: api
            - Type: audit
            - Type: authenticator
            - Type: controllerManager
            - Type: scheduler
      Name:
        Fn::Sub: ${ResourceNamePrefix}-${EKSClusterName}
      ResourcesVpcConfig:
        SecurityGroupIds:
          Ref: SecurityGroupIds
        SubnetIds:
          Ref: EksPrivateSubnetIds
      RoleArn:
        Fn::GetAtt:
          - ClusterRole
          - Arn
      Tags:
        - Key: aws-sagemaker-hyperpod-prerequiste
          Value:
            Fn::Sub: ${ResourceNamePrefix}-EKS-Cluster
      Version:
        Ref: KubernetesVersion
    Metadata:
      aws:cdk:path: EksCfnTemplate/EKSCluster
  VpcCNIAddOn:
    Type: AWS::EKS::Addon
    Properties:
      AddonName: vpc-cni
      ClusterName:
        Ref: EKSCluster
      ResolveConflicts: OVERWRITE
    Metadata:
      aws:cdk:path: EksCfnTemplate/VpcCNIAddOn
  KubeProxyAddOn:
    Type: AWS::EKS::Addon
    Properties:
      AddonName: kube-proxy
      ClusterName:
        Ref: EKSCluster
      ResolveConflicts: OVERWRITE
    Metadata:
      aws:cdk:path: EksCfnTemplate/KubeProxyAddOn
  CoreDNSAddOn:
    Type: AWS::EKS::Addon
    Properties:
      AddonName: coredns
      ClusterName:
        Ref: EKSCluster
      ResolveConflicts: OVERWRITE
    Metadata:
      aws:cdk:path: EksCfnTemplate/CoreDNSAddOn
  PodIdentityAddOn:
    Type: AWS::EKS::Addon
    Properties:
      AddonName: eks-pod-identity-agent
      ClusterName:
        Ref: EKSCluster
      ResolveConflicts: OVERWRITE
    Metadata:
      aws:cdk:path: EksCfnTemplate/PodIdentityAddOn
Outputs:
  EKSClusterArn:
    Description: ARN of the EKS Cluster
    Value:
      Fn::GetAtt:
        - EKSCluster
        - Arn
  EKSClusterName:
    Description: Name of the EKS Cluster
    Value:
      Ref: EKSCluster
  OIDCProviderURL:
    Description: The URL of the OIDC Provider for the EKS Cluster
    Value:
      Fn::GetAtt:
        - EKSCluster
        - OpenIdConnectIssuerUrl
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-OIDCProviderURL
  OIDCProviderURLWithoutProtocol:
    Description: The URL of the OIDC Provider without https:// prefix
    Value:
      Fn::Select:
        - 1
        - Fn::Split:
            - https://
            - Fn::GetAtt:
                - EKSCluster
                - OpenIdConnectIssuerUrl
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-OIDCProviderURLWithoutProtocol
