Description: Fsx Stack
Parameters:
  ResourceNamePrefix:
    Type: String
    Default: sagemaker-hyperpod-eks
    Description: Prefix to be used for all resources created by this template.
  HelmChartStatus:
    Type: String
    Default: HelmChartNotRequired
    Description: Conditionally wait on HelmChartStack if deployed
  EKSClusterName:
    Type: String
    Default: hyperpod-eks-cluster
    Description: The name of the EKS cluster you wish to use.
  CustomResourceS3Bucket:
    Type: String
    Default: aws-sagemaker-hyperpod-cluster-setup-us-east-2-prod
    Description: The name of the S3 bucket containing the custom resource.
  HelmLayerS3Key:
    Type: String
    Default: resources/artifacts/helm-lambda-layer.zip
    Description: The S3 key for the lambda layer zip file.
  HelmFunctionS3Key:
    Type: String
    Default: resources/artifacts/helm-lambda-function.zip
    Description: The S3 key for the lambda function zip file.
  FsxLayerS3Key:
    Type: String
    Default: resources/artifacts/fsx-lambda-layer.zip
    Description: The S3 key for the lambda layer zip file.
  FsxFunctionS3Key:
    Type: String
    Default: resources/artifacts/fsx-lambda-function.zip
    Description: The S3 key for the lambda function zip file.
  PrivateSubnetIds:
    Type: String
    Description: Comma-separated list of private subnet IDs
  FsxSubnetId:
    Type: String
    Description: The subnet id that will be used to create FSx
  FsxAvailabilityZoneId:
    Type: String
    Description: The availability zone to get subnet id that will be used to create FSx
  SecurityGroupIds:
    Type: String
    Description: ID of the security group to use
  PerUnitStorageThroughput:
    Type: Number
    Default: 250
    Description: Per unit storage throughput for the FSx file system
  DataCompressionType:
    Type: String
    Default: NONE
    AllowedValues:
      - NONE
      - LZ4
    Description: Data compression type for the FSx file system (NONE, LZ4)
  FileSystemTypeVersion:
    Type: Number
    Default: 2.15
    Description: File system type version for the FSx file system
  StorageCapacity:
    Type: Number
    Default: 1200
    Description: Storage capacity for the FSx file system in GiB
  DeploymentType:
    Type: String
    Default: PERSISTENT_2
    Description: Deployment type for the FSx file system
  FsxFileSystemId:
    Type: String
    Default: ''
    Description: Existing FSx for Lustre file system
Resources:
  FsxCustomResourceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - eks:DescribeCluster
                  - eks:TagResource
                Resource:
                  Fn::Sub: arn:aws:eks:${AWS::Region}:${AWS::AccountId}:cluster/${EKSClusterName}
          PolicyName:
            Fn::Sub: ${ResourceNamePrefix}-EKSAccess
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - iam:GetOpenIDConnectProvider
                  - iam:CreateOpenIDConnectProvider
                  - iam:TagOpenIDConnectProvider
                Resource:
                  Fn::Sub: arn:aws:iam::${AWS::AccountId}:oidc-provider/*
              - Effect: Allow
                Action:
                  - iam:GetRole
                  - iam:DetachRolePolicy
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:TagRole
                  - iam:AttachRolePolicy
                Resource:
                  Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/*
          PolicyName:
            Fn::Sub: ${ResourceNamePrefix}-IAMAccess
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:ListStacks
                  - cloudformation:CreateStack
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackResource
                  - cloudformation:DescribeStackResources
                  - cloudformation:SignalResource
                  - cloudformation:DeleteStack
                Resource:
                  Fn::Sub: arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/*
          PolicyName:
            Fn::Sub: ${ResourceNamePrefix}-CFNAccess
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ec2:DescribeSubnets
                Resource: '*'
          PolicyName:
            Fn::Sub: ${ResourceNamePrefix}-EC2Access
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - fsx:DescribeFileSystems
                Resource: '*'
          PolicyName:
            Fn::Sub: ${ResourceNamePrefix}-FSxAccess
    Metadata:
      aws:cdk:path: FsxCfnTemplate/FsxCustomResourceRole
  FsxCustomResourceAccessEntry:
    Type: AWS::EKS::AccessEntry
    Properties:
      AccessPolicies:
        - AccessScope:
            Type: cluster
          PolicyArn: arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy
      ClusterName:
        Ref: EKSClusterName
      PrincipalArn:
        Fn::GetAtt:
          - FsxCustomResourceRole
          - Arn
    Metadata:
      aws:cdk:path: FsxCfnTemplate/FsxCustomResourceAccessEntry
  FsxCustomResourceLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleArchitectures:
        - x86_64
      CompatibleRuntimes:
        - python3.9
        - python3.10
        - python3.11
        - python3.12
      Content:
        S3Bucket:
          Ref: CustomResourceS3Bucket
        S3Key:
          Ref: FsxLayerS3Key
      Description: Lambda Layer for kubectl, helm, and git tools
      LayerName:
        Fn::Sub: ${ResourceNamePrefix}-fsx-layer1
    Metadata:
      aws:cdk:path: FsxCfnTemplate/FsxCustomResourceLayer
  FsxCustomResourceFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: CustomResourceS3Bucket
        S3Key:
          Ref: FsxFunctionS3Key
      Environment:
        Variables:
          CLUSTER_NAME:
            Ref: EKSClusterName
          PRIVATE_SUBNET_IDS:
            Ref: PrivateSubnetIds
          FSX_SUBNETID:
            Ref: FsxSubnetId
          FSX_AVAILABILITY_ZONE:
            Ref: FsxAvailabilityZoneId
          SECURITY_GROUP_ID:
            Ref: SecurityGroupIds
          PER_UNIT_STORAGE_THROUGHPUT:
            Ref: PerUnitStorageThroughput
          DATA_COMPRESSION_TYPE:
            Ref: DataCompressionType
          FILE_SYSTEM_TYPE_VERSION:
            Ref: FileSystemTypeVersion
          STORAGE_CAPACITY:
            Ref: StorageCapacity
          DEPLOYMENT_TYPE:
            Ref: DeploymentType
          FSX_FILE_SYSTEM_ID:
            Ref: FsxFileSystemId
          PATH: /opt/python/bin:/var/lang/bin:/usr/local/bin:/usr/bin/:/bin
          GIT_EXEC_PATH: /opt/python/libexec/git-core
          KUBECONFIG: /tmp/.kube/config
          LD_LIBRARY_PATH: /opt/python/lib
      FunctionName:
        Fn::Sub: ${ResourceNamePrefix}fsxfunc1
      Handler: lambda_function.lambda_handler
      Layers:
        - Ref: FsxCustomResourceLayer
      Role:
        Fn::GetAtt:
          - FsxCustomResourceRole
          - Arn
      Runtime: python3.12
      Timeout: 600
    DependsOn:
      - FsxCustomResourceAccessEntry
    Metadata:
      aws:cdk:path: FsxCfnTemplate/FsxCustomResourceFunction
  FsxCustomResourceStep1:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - FsxCustomResourceFunction
          - Arn
    Metadata:
      aws:cdk:path: FsxCfnTemplate/FsxCustomResourceStep1
  FSxCsiAddon:
    Type: AWS::EKS::Addon
    Properties:
      AddonName: aws-fsx-csi-driver
      ClusterName:
        Ref: EKSClusterName
      PreserveOnDelete: false
      ResolveConflicts: OVERWRITE
    DependsOn:
      - FsxCustomResourceStep1
    Metadata:
      aws:cdk:path: FsxCfnTemplate/FSxCsiAddon
  FsxCustomResourceStep2:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - FsxCustomResourceFunction
          - Arn
    DependsOn:
      - FSxCsiAddon
    Metadata:
      aws:cdk:path: FsxCfnTemplate/FsxCustomResourceStep2
Outputs:
  FsxDeploymentComplete:
    Description: Indicates fsx deployment is complete
    Value: FsxDeploymentComplete
