Description: HyperPod Cluster Stack
Parameters:
  ResourceNamePrefix:
    Type: String
    Default: sagemaker-hyperpod-eks
    Description: Prefix to be used for all resources created by this template.
  HelmChartStatus:
    Type: String
    Default: HelmChartNotRequired
    Description: Conditionally wait on HelmChartStack if deployed
  FsxStatus:
    Type: String
    Default: FsxNotRequired
    Description: Conditionally wait on FsxStack if deployed
  HyperPodClusterName:
    Type: String
    Default: ml-cluster
    Description: Name of SageMaker HyperPod Cluster.
  NodeRecovery:
    Type: String
    Default: Automatic
    AllowedValues:
      - Automatic
      - None
    Description: Enable or disable the automatic node recovery feature
  NodeProvisioningMode:
    Type: String
    Default: ''
    AllowedValues:
      - Continuous
      - ''
    Description: Enable or disable the continuous provisioning mode
  EKSClusterName:
    Type: String
    Default: hyperpod-eks-cluster
    Description: The name of the EKS cluster you wish to use.
  SecurityGroupIds:
    Type: String
  PrivateSubnetIds:
    Type: String
    Description: Comma-separated list of private subnet IDs
  CustomResourceS3Bucket:
    Type: String
    Default: ws-assets-prod-iad-r-pdx-f3b3f9f1a7d6a3d0
    Description: The name of the S3 bucket containing the custom resource.
  SageMakerIAMRoleName:
    Type: String
    Default: sagemaker-hyperpod-eks-role
    Description: The name of the IAM role that SageMaker will use to access the AWS resources on your behalf.
  S3BucketName:
    Type: String
    Default: sagemaker-hyperpod-eks-bucket
    Description: The name of the S3 bucket used to store the cluster lifecycle scripts.
  OnCreatePath:
    Type: String
    Default: on_create.sh
    Description: >-
      The file name of lifecycle script for the general purpose instance group. This script runs during cluster
      creation.
  Tags:
    Type: String
    Default: ''
    Description: Custom tags for managing the SageMaker HyperPod cluster as an AWS resource.
  InstanceGroupSettings1:
    Type: String
    Default: '[]'
    Description: JSON array string containing instance group configurations.
  RigSettings1:
    Type: String
    Default: '[]'
    Description: JSON array string containing restricted instance group configurations.
  InstanceGroupSettings2:
    Type: String
    Default: '[]'
    Description: JSON array string containing instance group configurations.
  RigSettings2:
    Type: String
    Default: '[]'
    Description: JSON array string containing restricted instance group configurations.
  InstanceGroupSettings3:
    Type: String
    Default: '[]'
    Description: JSON array string containing instance group configurations.
  RigSettings3:
    Type: String
    Default: '[]'
    Description: JSON array string containing restricted instance group configurations.
  InstanceGroupSettings4:
    Type: String
    Default: '[]'
    Description: JSON array string containing instance group configurations.
  RigSettings4:
    Type: String
    Default: '[]'
    Description: JSON array string containing restricted instance group configurations.
  InstanceGroupSettings5:
    Type: String
    Default: '[]'
    Description: JSON array string containing instance group configurations.
  RigSettings5:
    Type: String
    Default: '[]'
    Description: JSON array string containing restricted instance group configurations.
  InstanceGroupSettings6:
    Type: String
    Default: '[]'
    Description: JSON array string containing instance group configurations.
  RigSettings6:
    Type: String
    Default: '[]'
    Description: JSON array string containing restricted instance group configurations.
  InstanceGroupSettings7:
    Type: String
    Default: '[]'
    Description: JSON array string containing instance group configurations.
  RigSettings7:
    Type: String
    Default: '[]'
    Description: JSON array string containing restricted instance group configurations.
  InstanceGroupSettings8:
    Type: String
    Default: '[]'
    Description: JSON array string containing instance group configurations.
  RigSettings8:
    Type: String
    Default: '[]'
    Description: JSON array string containing restricted instance group configurations.
  InstanceGroupSettings9:
    Type: String
    Default: '[]'
    Description: JSON array string containing instance group configurations.
  RigSettings9:
    Type: String
    Default: '[]'
    Description: JSON array string containing restricted instance group configurations.
  InstanceGroupSettings10:
    Type: String
    Default: '[]'
    Description: JSON array string containing instance group configurations.
  RigSettings10:
    Type: String
    Default: '[]'
    Description: JSON array string containing restricted instance group configurations.
  InstanceGroupSettings11:
    Type: String
    Default: '[]'
    Description: JSON array string containing instance group configurations.
  RigSettings11:
    Type: String
    Default: '[]'
    Description: JSON array string containing restricted instance group configurations.
  InstanceGroupSettings12:
    Type: String
    Default: '[]'
    Description: JSON array string containing instance group configurations.
  RigSettings12:
    Type: String
    Default: '[]'
    Description: JSON array string containing restricted instance group configurations.
  InstanceGroupSettings13:
    Type: String
    Default: '[]'
    Description: JSON array string containing instance group configurations.
  RigSettings13:
    Type: String
    Default: '[]'
    Description: JSON array string containing restricted instance group configurations.
  InstanceGroupSettings14:
    Type: String
    Default: '[]'
    Description: JSON array string containing instance group configurations.
  RigSettings14:
    Type: String
    Default: '[]'
    Description: JSON array string containing restricted instance group configurations.
  InstanceGroupSettings15:
    Type: String
    Default: '[]'
    Description: JSON array string containing instance group configurations.
  RigSettings15:
    Type: String
    Default: '[]'
    Description: JSON array string containing restricted instance group configurations.
  InstanceGroupSettings16:
    Type: String
    Default: '[]'
    Description: JSON array string containing instance group configurations.
  RigSettings16:
    Type: String
    Default: '[]'
    Description: JSON array string containing restricted instance group configurations.
  InstanceGroupSettings17:
    Type: String
    Default: '[]'
    Description: JSON array string containing instance group configurations.
  RigSettings17:
    Type: String
    Default: '[]'
    Description: JSON array string containing restricted instance group configurations.
  InstanceGroupSettings18:
    Type: String
    Default: '[]'
    Description: JSON array string containing instance group configurations.
  RigSettings18:
    Type: String
    Default: '[]'
    Description: JSON array string containing restricted instance group configurations.
  InstanceGroupSettings19:
    Type: String
    Default: '[]'
    Description: JSON array string containing instance group configurations.
  RigSettings19:
    Type: String
    Default: '[]'
    Description: JSON array string containing restricted instance group configurations.
  InstanceGroupSettings20:
    Type: String
    Default: '[]'
    Description: JSON array string containing instance group configurations.
  RigSettings20:
    Type: String
    Default: '[]'
    Description: JSON array string containing restricted instance group configurations.
Resources:
  HyperPodClusterCustomResourceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: iam:PassRole
                Resource:
                  Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/${SageMakerIAMRoleName}
              - Effect: Allow
                Action:
                  - sagemaker:ListClusters
                  - sagemaker:ListClusterNodes
                  - sagemaker:CreateCluster
                  - sagemaker:DeleteCluster
                  - sagemaker:UpdateCluster
                  - sagemaker:UpdateClusterSoftware
                  - sagemaker:BatchDeleteClusterNodes
                  - sagemaker:DescribeCluster
                  - sagemaker:DescribeClusterNode
                Resource:
                  - Fn::Sub: arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:cluster/*
                  - Fn::Sub: arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:training-plan/*
                  - Fn::Sub: arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:reserved-capacity/*
              - Effect: Allow
                Action:
                  - sagemaker:ListComputeQuotas
                  - sagemaker:ListClusterSchedulerConfig
                  - sagemaker:TagResource
                  - sagemaker:CreateTags
                  - sagemaker:AddTags
                  - sagemaker:UntagResource
                Resource: '*'
              - Effect: Allow
                Action:
                  - sagemaker:DeleteComputeQuota
                Resource:
                  - Fn::Sub: arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:compute-quota/*
              - Effect: Allow
                Action:
                  - sagemaker:DeleteClusterSchedulerConfig
                Resource:
                  Fn::Sub: arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:cluster-scheduler-config/*
              - Effect: Allow
                Action:
                  - eks:DescribeCluster
                  - eks:CreateAccessEntry
                Resource:
                  Fn::Sub: arn:aws:eks:${AWS::Region}:${AWS::AccountId}:cluster/*
              - Effect: Allow
                Action:
                  - eks:DescribeAccessEntry
                  - eks:DeleteAccessEntry
                  - eks:AssociateAccessPolicy
                Resource:
                  Fn::Sub: arn:aws:eks:${AWS::Region}:${AWS::AccountId}:access-entry/*
              - Effect: Allow
                Action:
                  - iam:CreateServiceLinkedRole
                Resource:
                  Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/*
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:DeleteObject
                Resource:
                  - Fn::Sub:
                      - arn:aws:s3:::${S3BucketName}/*
                      - S3BucketName:
                          Ref: S3BucketName
              - Effect: Allow
                Action:
                  - ec2:DescribeSecurityGroups
                  - ec2:DescribeSubnets
                  - ec2:DescribeVpcs
                Resource: '*'
          PolicyName:
            Fn::Sub: ${ResourceNamePrefix}-Policy
    Metadata:
      aws:cdk:path: HyperPodClusterCfnTemplate/HyperPodClusterCustomResourceRole
  hyperPodCustomResourceFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: CustomResourceS3Bucket
        S3Key: resources/artifacts/hp-lambda-function.zip
      Environment:
        Variables:
          HYPER_POD_CLUSTER_NAME:
            Ref: HyperPodClusterName
          NODE_RECOVERY:
            Ref: NodeRecovery
          NODE_PROVISIONING_MODE:
            Ref: NodeProvisioningMode
          EKS_CLUSTER_ARN:
            Fn::Sub: arn:aws:eks:${AWS::Region}:${AWS::AccountId}:cluster/${EKSClusterName}
          SECURITY_GROUP_IDS:
            Ref: SecurityGroupIds
          PRIVATE_SUBNET_IDS:
            Ref: PrivateSubnetIds
          SAGEMAKER_IAM_ROLE_NAME:
            Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/${SageMakerIAMRoleName}
          S3_BUCKET_NAME:
            Ref: S3BucketName
          ON_CREATE_PATH:
            Ref: OnCreatePath
          CLUSTER_TAGS:
            Ref: Tags
          INSTANCE_GROUP_SETTINGS1:
            Ref: InstanceGroupSettings1
          RIG_SETTINGS1:
            Ref: RigSettings1
          INSTANCE_GROUP_SETTINGS2:
            Ref: InstanceGroupSettings2
          RIG_SETTINGS2:
            Ref: RigSettings2
          INSTANCE_GROUP_SETTINGS3:
            Ref: InstanceGroupSettings3
          RIG_SETTINGS3:
            Ref: RigSettings3
          INSTANCE_GROUP_SETTINGS4:
            Ref: InstanceGroupSettings4
          RIG_SETTINGS4:
            Ref: RigSettings4
          INSTANCE_GROUP_SETTINGS5:
            Ref: InstanceGroupSettings5
          RIG_SETTINGS5:
            Ref: RigSettings5
          INSTANCE_GROUP_SETTINGS6:
            Ref: InstanceGroupSettings6
          RIG_SETTINGS6:
            Ref: RigSettings6
          INSTANCE_GROUP_SETTINGS7:
            Ref: InstanceGroupSettings7
          RIG_SETTINGS7:
            Ref: RigSettings7
          INSTANCE_GROUP_SETTINGS8:
            Ref: InstanceGroupSettings8
          RIG_SETTINGS8:
            Ref: RigSettings8
          INSTANCE_GROUP_SETTINGS9:
            Ref: InstanceGroupSettings9
          RIG_SETTINGS9:
            Ref: RigSettings9
          INSTANCE_GROUP_SETTINGS10:
            Ref: InstanceGroupSettings10
          RIG_SETTINGS10:
            Ref: RigSettings10
          INSTANCE_GROUP_SETTINGS11:
            Ref: InstanceGroupSettings11
          RIG_SETTINGS11:
            Ref: RigSettings11
          INSTANCE_GROUP_SETTINGS12:
            Ref: InstanceGroupSettings12
          RIG_SETTINGS12:
            Ref: RigSettings12
          INSTANCE_GROUP_SETTINGS13:
            Ref: InstanceGroupSettings13
          RIG_SETTINGS13:
            Ref: RigSettings13
          INSTANCE_GROUP_SETTINGS14:
            Ref: InstanceGroupSettings14
          RIG_SETTINGS14:
            Ref: RigSettings14
          INSTANCE_GROUP_SETTINGS15:
            Ref: InstanceGroupSettings15
          RIG_SETTINGS15:
            Ref: RigSettings15
          INSTANCE_GROUP_SETTINGS16:
            Ref: InstanceGroupSettings16
          RIG_SETTINGS16:
            Ref: RigSettings16
          INSTANCE_GROUP_SETTINGS17:
            Ref: InstanceGroupSettings17
          RIG_SETTINGS17:
            Ref: RigSettings17
          INSTANCE_GROUP_SETTINGS18:
            Ref: InstanceGroupSettings18
          RIG_SETTINGS18:
            Ref: RigSettings18
          INSTANCE_GROUP_SETTINGS19:
            Ref: InstanceGroupSettings19
          RIG_SETTINGS19:
            Ref: RigSettings19
          INSTANCE_GROUP_SETTINGS20:
            Ref: InstanceGroupSettings20
          RIG_SETTINGS20:
            Ref: RigSettings20
          NUMBER_OF_INSTANCE_GROUPS: '20'
      FunctionName:
        Fn::Sub:
          - ${ResourceNamePrefix}hpfunc
          - ResourceNamePrefix:
              Ref: ResourceNamePrefix
      Handler: lambda_function.lambda_handler
      Role:
        Fn::GetAtt:
          - HyperPodClusterCustomResourceRole
          - Arn
      Runtime: python3.12
      Timeout: 900
    Metadata:
      aws:cdk:path: HyperPodClusterCfnTemplate/hyperPodCustomResourceFunction
  HpLambdaCustomResource:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - hyperPodCustomResourceFunction
          - Arn
    Metadata:
      aws:cdk:path: HyperPodClusterCfnTemplate/HpLambdaCustomResource
Outputs:
  HyperPodClusterTemplateUrlOutput:
    Description: Template url of the SageMaker HyperPod Cluster
    Value:
      Fn::GetAtt:
        - HpLambdaCustomResource
        - TemplateUrl
