Description: Inference Operator Service Accounts Stack
Parameters:
  ResourceNamePrefix:
    Type: String
    Default: sagemaker-hyperpod-eks
    Description: Prefix to be used for all resources created by this template.
  EKSClusterName:
    Type: String
    Default: hyperpod-eks-cluster
    Description: The name of the EKS cluster you wish to use.
  AlbControllerPolicyArn:
    Type: String
    Description: IAM Role ARN for HyperPod inference operator.
  S3CsiPolicyArn:
    Type: String
    Description: IAM Role ARN for HyperPod inference operator.
  OIDCProviderURLWithoutProtocol:
    Type: String
    Description: The URL of the OIDC Provider without https:// prefix.
  CustomResourceS3Bucket:
    Type: String
    Default: aws-sagemaker-hyperpod-cluster-setup-us-east-2-prod
    Description: The name of the S3 bucket containing the custom resource.
  LayerS3Key:
    Type: String
    Default: resources/artifacts/inf-sa-creation-lambda-layer.zip
    Description: The S3 key for the lambda layer zip file.
  FunctionS3Key:
    Type: String
    Default: resources/artifacts/inf-sa-creation-lambda-function.zip
    Description: The S3 key for the lambda function zip file.
Resources:
  InferenceSACreationCustomResourceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - eks:DescribeCluster
                  - eks:TagResource
                Resource:
                  Fn::Sub: arn:aws:eks:${AWS::Region}:${AWS::AccountId}:cluster/${EKSClusterName}
          PolicyName:
            Fn::Sub: ${ResourceNamePrefix}-EKSAccess
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:ListStacks
                  - cloudformation:CreateStack
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackResource
                  - cloudformation:DescribeStackResources
                  - cloudformation:SignalResource
                  - cloudformation:DeleteStack
                Resource: '*'
          PolicyName:
            Fn::Sub: ${ResourceNamePrefix}-CFNAccess
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - iam:GetOpenIDConnectProvider
                  - iam:CreateOpenIDConnectProvider
                  - iam:TagOpenIDConnectProvider
                Resource:
                  Fn::Sub: arn:aws:iam::${AWS::AccountId}:oidc-provider/${OIDCProviderURLWithoutProtocol}
              - Effect: Allow
                Action:
                  - iam:GetRole
                  - iam:DetachRolePolicy
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:TagRole
                  - iam:AttachRolePolicy
                Resource:
                  Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/*
          PolicyName:
            Fn::Sub: ${ResourceNamePrefix}-IAMAccess
    Metadata:
      aws:cdk:path: InferenceServiceAccountCfnTemplate/InferenceSACreationCustomResourceRole
  ServiceAccountsCustomResourceAccessEntry:
    Type: AWS::EKS::AccessEntry
    Properties:
      AccessPolicies:
        - AccessScope:
            Type: cluster
          PolicyArn: arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy
      ClusterName:
        Ref: EKSClusterName
      PrincipalArn:
        Fn::GetAtt:
          - InferenceSACreationCustomResourceRole
          - Arn
    Metadata:
      aws:cdk:path: InferenceServiceAccountCfnTemplate/ServiceAccountsCustomResourceAccessEntry
  ServiceAccountsCustomResourceLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleArchitectures:
        - x86_64
      CompatibleRuntimes:
        - python3.9
        - python3.10
        - python3.11
        - python3.12
      Content:
        S3Bucket:
          Ref: CustomResourceS3Bucket
        S3Key:
          Ref: LayerS3Key
      Description: Lambda Layer for kubectl, and eksctl
      LayerName:
        Fn::Sub: ${ResourceNamePrefix}-inf-sa-creation-layer
    Metadata:
      aws:cdk:path: InferenceServiceAccountCfnTemplate/ServiceAccountsCustomResourceLayer
  ServiceAccountsCustomResourceFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: CustomResourceS3Bucket
        S3Key:
          Ref: FunctionS3Key
      Environment:
        Variables:
          CLUSTER_NAME:
            Ref: EKSClusterName
          ACCOUNT_ID:
            Ref: AWS::AccountId
          EKS_CLUSTER_NAME:
            Ref: EKSClusterName
          ALB_CONTROLLER_SA_NAME: aws-load-balancer-controller
          ALB_CONTROLLER_IAM_POLICY_ARN:
            Ref: AlbControllerPolicyArn
          S3_CSI_SA_NAME: s3-csi-driver-sa
          S3_CSI_IAM_POLICY_ARN:
            Ref: S3CsiPolicyArn
          S3_CSI_IAM_ROLE_NAME:
            Fn::Sub: ${ResourceNamePrefix}-inf-s3-csi-driver-role
          PATH: /opt/python/bin:/var/lang/bin:/usr/local/bin:/usr/bin/:/bin
          GIT_EXEC_PATH: /opt/python/libexec/git-core
          KUBECONFIG: /tmp/.kube/config
          LD_LIBRARY_PATH: /opt/python/lib
      FunctionName:
        Fn::Sub: ${ResourceNamePrefix}-infsa
      Handler: lambda_function.lambda_handler
      Layers:
        - Ref: ServiceAccountsCustomResourceLayer
      Role:
        Fn::GetAtt:
          - InferenceSACreationCustomResourceRole
          - Arn
      Runtime: python3.12
      Timeout: 600
    DependsOn:
      - ServiceAccountsCustomResourceAccessEntry
    Metadata:
      aws:cdk:path: InferenceServiceAccountCfnTemplate/ServiceAccountsCustomResourceFunction
  InferenceSACreationCustomResource:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - ServiceAccountsCustomResourceFunction
          - Arn
    Metadata:
      aws:cdk:path: InferenceServiceAccountCfnTemplate/InferenceSACreationCustomResource
Outputs:
  InferenceServiceAccountsCreationComplete:
    Description: Indicates inference service accounts creation is complete
    Value: InferenceServiceAccountsCreationComplete
