Description: Inference Operator Helm Chart Stack
Parameters:
  ResourceNamePrefix:
    Type: String
    Default: sagemaker-hyperpod-eks
    Description: Prefix to be used for all resources created by this template.
  EKSClusterName:
    Type: String
    Default: hyperpod-eks-cluster
    Description: The name of the EKS cluster you wish to use.
  HelmRepoUrl:
    Type: String
    Default: https://github.com/aws/sagemaker-hyperpod-cli.git
    Description: The URL of the Helm repo containing the HyperPod Helm chart.
  HelmRepoPath:
    Type: String
    Default: helm_chart/HyperPodHelmChart/charts/inference-operator
    Description: The path to the HyperPod Helm chart in the Helm repo.
  Namespace:
    Type: String
    Default: kube-system
    Description: The namespace to deploy the HyperPod Helm chart into.
  HPClusterArn:
    Type: String
    Description: ARN of the HyperPod cluster.
  HyperpodInferenceRoleArn:
    Type: String
    Description: IAM Role ARN for HyperPod inference operator.
  JumpstartGatedModelDownloadRoleArn:
    Type: String
    Description: IAM Role ARN for HyperPod inference operator to download JumpStart gated model.
  KedaRoleArn:
    Type: String
    Description: IAM Role ARN for HyperPod inference operator to interact with keda.
  TLSBucketName:
    Type: String
    Description: S3 bucket name where TLS certificate is stored.
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID used by the EKS cluster.
  CustomResourceS3Bucket:
    Type: String
    Default: aws-sagemaker-hyperpod-cluster-setup-us-east-2-prod
    Description: The name of the S3 bucket containing the custom resource.
  LayerS3Key:
    Type: String
    Default: resources/artifacts/inf-helm-lambda-layer.zip
    Description: The S3 key for the lambda layer zip file.
  FunctionS3Key:
    Type: String
    Default: resources/artifacts/inf-helm-lambda-function.zip
    Description: The S3 key for the lambda function zip file.
Resources:
  InferenceHelmCustomResourceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - eks:DescribeCluster
                Resource:
                  Fn::Sub: arn:aws:eks:${AWS::Region}:${AWS::AccountId}:cluster/${EKSClusterName}
          PolicyName:
            Fn::Sub: ${ResourceNamePrefix}-EKSAccess
    Metadata:
      aws:cdk:path: InferenceHelmChartCfnTemplate/InferenceHelmCustomResourceRole
  InferenceHelmCustomResourceAccessEntry:
    Type: AWS::EKS::AccessEntry
    Properties:
      AccessPolicies:
        - AccessScope:
            Type: cluster
          PolicyArn: arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy
      ClusterName:
        Ref: EKSClusterName
      PrincipalArn:
        Fn::GetAtt:
          - InferenceHelmCustomResourceRole
          - Arn
    Metadata:
      aws:cdk:path: InferenceHelmChartCfnTemplate/InferenceHelmCustomResourceAccessEntry
  HelmCustomResourceLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleArchitectures:
        - x86_64
      CompatibleRuntimes:
        - python3.9
        - python3.10
        - python3.11
        - python3.12
      Content:
        S3Bucket:
          Ref: CustomResourceS3Bucket
        S3Key:
          Ref: LayerS3Key
      Description: Lambda Layer for kubectl, helm, and git tools
      LayerName:
        Fn::Sub: ${ResourceNamePrefix}-inf-helm-layer
    Metadata:
      aws:cdk:path: InferenceHelmChartCfnTemplate/HelmCustomResourceLayer
  HelmCustomResourceFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: CustomResourceS3Bucket
        S3Key:
          Ref: FunctionS3Key
      Environment:
        Variables:
          CLUSTER_NAME:
            Ref: EKSClusterName
          ACCOUNT_ID:
            Ref: AWS::AccountId
          HYPERPOD_CLI_GITHUB_REPO_URL:
            Ref: HelmRepoUrl
          HYPERPOD_CLI_GITHUB_REPO_BRANCH: main
          CHART_PATH:
            Ref: HelmRepoPath
          NAMESPACE:
            Ref: Namespace
          EKS_CLUSTER_NAME:
            Ref: EKSClusterName
          HP_CLUSTER_ARN:
            Ref: HPClusterArn
          HYPERPOD_INFERENCE_ROLE_ARN:
            Ref: HyperpodInferenceRoleArn
          JUMPSTART_GATED_ROLE_ARN:
            Ref: JumpstartGatedModelDownloadRoleArn
          S3_CSI_ROLE_NAME:
            Fn::Sub: ${ResourceNamePrefix}-inf-s3-csi-driver-role
          KEDA_ROLE_ARN:
            Ref: KedaRoleArn
          TLS_BUCKET_NAME:
            Ref: TLSBucketName
          VPC_ID:
            Ref: VpcId
          PATH: /opt/python/bin:/var/lang/bin:/usr/local/bin:/usr/bin/:/bin
          GIT_EXEC_PATH: /opt/python/libexec/git-core
          KUBECONFIG: /tmp/.kube/config
          LD_LIBRARY_PATH: /opt/python/lib
      FunctionName:
        Fn::Sub: ${ResourceNamePrefix}infhelm
      Handler: lambda_function.lambda_handler
      Layers:
        - Ref: HelmCustomResourceLayer
      MemorySize: 2048
      Role:
        Fn::GetAtt:
          - InferenceHelmCustomResourceRole
          - Arn
      Runtime: python3.12
      Timeout: 900
    DependsOn:
      - InferenceHelmCustomResourceAccessEntry
    Metadata:
      aws:cdk:path: InferenceHelmChartCfnTemplate/HelmCustomResourceFunction
  HelmCustomResource:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - HelmCustomResourceFunction
          - Arn
    Metadata:
      aws:cdk:path: InferenceHelmChartCfnTemplate/HelmCustomResource
Outputs:
  InferenceHelmChartDeploymentComplete:
    Description: Indicates Inference Helm chart deployment is complete
    Value: InferenceHelmChartDeploymentComplete
