Description: VPC Stack
Parameters:
  ResourceNamePrefix:
    Type: String
    Default: sagemaker-hyperpod-eks
    Description: Prefix to be used for all resources created by this template.
  VpcCIDR:
    Type: String
    Default: 10.192.0.0/16
    Description: The IP range (CIDR notation) for the VPC.
  AvailabilityZoneIds:
    Type: CommaDelimitedList
    Default: use2-az2,,,,
    Description: List of AZs to deploy subnets in (up to 5)
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        Ref: VpcCIDR
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: aws-sagemaker-hyperpod-prerequiste
          Value:
            Fn::Sub: ${ResourceNamePrefix}-VPC
    Metadata:
      aws:cdk:path: VpcCfnTemplate/VPC
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: aws-sagemaker-hyperpod-prerequiste
          Value:
            Fn::Sub: ${ResourceNamePrefix}-IGW
    Metadata:
      aws:cdk:path: VpcCfnTemplate/InternetGateway
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId:
        Ref: InternetGateway
      VpcId:
        Ref: VPC
    Metadata:
      aws:cdk:path: VpcCfnTemplate/InternetGatewayAttachment
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: aws-sagemaker-hyperpod-prerequiste
          Value:
            Fn::Sub: ${ResourceNamePrefix}-Public-Routes
      VpcId:
        Ref: VPC
    Metadata:
      aws:cdk:path: VpcCfnTemplate/PublicRouteTable
  DefaultPublicRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway
      RouteTableId:
        Ref: PublicRouteTable
    DependsOn:
      - InternetGatewayAttachment
    Metadata:
      aws:cdk:path: VpcCfnTemplate/DefaultPublicRoute
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZoneId:
        Fn::Select:
          - 0
          - Ref: AvailabilityZoneIds
      CidrBlock:
        Fn::Join:
          - ''
          - - Fn::Select:
                - 0
                - Fn::Split:
                    - .
                    - Fn::Select:
                        - 0
                        - Fn::Split:
                            - /
                            - Ref: VpcCIDR
            - .
            - Fn::Select:
                - 1
                - Fn::Split:
                    - .
                    - Fn::Select:
                        - 0
                        - Fn::Split:
                            - /
                            - Ref: VpcCIDR
            - .0.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: aws-sagemaker-hyperpod-prerequiste
          Value:
            Fn::Sub: ${ResourceNamePrefix}-Public-Subnet1
      VpcId:
        Ref: VPC
    Metadata:
      aws:cdk:path: VpcCfnTemplate/PublicSubnet1
    Condition: HasAZ1
  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PublicRouteTable
      SubnetId:
        Ref: PublicSubnet1
    Metadata:
      aws:cdk:path: VpcCfnTemplate/PublicSubnet1RouteTableAssociation
    Condition: HasAZ1
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZoneId:
        Fn::Select:
          - 1
          - Ref: AvailabilityZoneIds
      CidrBlock:
        Fn::Join:
          - ''
          - - Fn::Select:
                - 0
                - Fn::Split:
                    - .
                    - Fn::Select:
                        - 0
                        - Fn::Split:
                            - /
                            - Ref: VpcCIDR
            - .
            - Fn::Select:
                - 1
                - Fn::Split:
                    - .
                    - Fn::Select:
                        - 0
                        - Fn::Split:
                            - /
                            - Ref: VpcCIDR
            - .32.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: aws-sagemaker-hyperpod-prerequiste
          Value:
            Fn::Sub: ${ResourceNamePrefix}-Public-Subnet2
      VpcId:
        Ref: VPC
    Metadata:
      aws:cdk:path: VpcCfnTemplate/PublicSubnet2
    Condition: HasAZ2
  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PublicRouteTable
      SubnetId:
        Ref: PublicSubnet2
    Metadata:
      aws:cdk:path: VpcCfnTemplate/PublicSubnet2RouteTableAssociation
    Condition: HasAZ2
  PublicSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZoneId:
        Fn::Select:
          - 2
          - Ref: AvailabilityZoneIds
      CidrBlock:
        Fn::Join:
          - ''
          - - Fn::Select:
                - 0
                - Fn::Split:
                    - .
                    - Fn::Select:
                        - 0
                        - Fn::Split:
                            - /
                            - Ref: VpcCIDR
            - .
            - Fn::Select:
                - 1
                - Fn::Split:
                    - .
                    - Fn::Select:
                        - 0
                        - Fn::Split:
                            - /
                            - Ref: VpcCIDR
            - .64.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: aws-sagemaker-hyperpod-prerequiste
          Value:
            Fn::Sub: ${ResourceNamePrefix}-Public-Subnet3
      VpcId:
        Ref: VPC
    Metadata:
      aws:cdk:path: VpcCfnTemplate/PublicSubnet3
    Condition: HasAZ3
  PublicSubnet3RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PublicRouteTable
      SubnetId:
        Ref: PublicSubnet3
    Metadata:
      aws:cdk:path: VpcCfnTemplate/PublicSubnet3RouteTableAssociation
    Condition: HasAZ3
  PublicSubnet4:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZoneId:
        Fn::Select:
          - 3
          - Ref: AvailabilityZoneIds
      CidrBlock:
        Fn::Join:
          - ''
          - - Fn::Select:
                - 0
                - Fn::Split:
                    - .
                    - Fn::Select:
                        - 0
                        - Fn::Split:
                            - /
                            - Ref: VpcCIDR
            - .
            - Fn::Select:
                - 1
                - Fn::Split:
                    - .
                    - Fn::Select:
                        - 0
                        - Fn::Split:
                            - /
                            - Ref: VpcCIDR
            - .96.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: aws-sagemaker-hyperpod-prerequiste
          Value:
            Fn::Sub: ${ResourceNamePrefix}-Public-Subnet4
      VpcId:
        Ref: VPC
    Metadata:
      aws:cdk:path: VpcCfnTemplate/PublicSubnet4
    Condition: HasAZ4
  PublicSubnet4RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PublicRouteTable
      SubnetId:
        Ref: PublicSubnet4
    Metadata:
      aws:cdk:path: VpcCfnTemplate/PublicSubnet4RouteTableAssociation
    Condition: HasAZ4
  PublicSubnet5:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZoneId:
        Fn::Select:
          - 4
          - Ref: AvailabilityZoneIds
      CidrBlock:
        Fn::Join:
          - ''
          - - Fn::Select:
                - 0
                - Fn::Split:
                    - .
                    - Fn::Select:
                        - 0
                        - Fn::Split:
                            - /
                            - Ref: VpcCIDR
            - .
            - Fn::Select:
                - 1
                - Fn::Split:
                    - .
                    - Fn::Select:
                        - 0
                        - Fn::Split:
                            - /
                            - Ref: VpcCIDR
            - .128.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: aws-sagemaker-hyperpod-prerequiste
          Value:
            Fn::Sub: ${ResourceNamePrefix}-Public-Subnet5
      VpcId:
        Ref: VPC
    Metadata:
      aws:cdk:path: VpcCfnTemplate/PublicSubnet5
    Condition: HasAZ5
  PublicSubnet5RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PublicRouteTable
      SubnetId:
        Ref: PublicSubnet5
    Metadata:
      aws:cdk:path: VpcCfnTemplate/PublicSubnet5RouteTableAssociation
    Condition: HasAZ5
  NatGatewayEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
    DependsOn:
      - InternetGatewayAttachment
    Metadata:
      aws:cdk:path: VpcCfnTemplate/NatGatewayEIP
    Condition: HasAZ1
  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Fn::GetAtt:
          - NatGatewayEIP
          - AllocationId
      SubnetId:
        Ref: PublicSubnet1
    Metadata:
      aws:cdk:path: VpcCfnTemplate/NatGateway
    Condition: HasAZ1
Conditions:
  HasAZ1:
    Fn::Not:
      - Fn::Equals:
          - Fn::Select:
              - 0
              - Ref: AvailabilityZoneIds
          - ''
  HasAZ2:
    Fn::Not:
      - Fn::Equals:
          - Fn::Select:
              - 1
              - Ref: AvailabilityZoneIds
          - ''
  HasAZ3:
    Fn::Not:
      - Fn::Equals:
          - Fn::Select:
              - 2
              - Ref: AvailabilityZoneIds
          - ''
  HasAZ4:
    Fn::Not:
      - Fn::Equals:
          - Fn::Select:
              - 3
              - Ref: AvailabilityZoneIds
          - ''
  HasAZ5:
    Fn::Not:
      - Fn::Equals:
          - Fn::Select:
              - 4
              - Ref: AvailabilityZoneIds
          - ''
Outputs:
  VpcId:
    Description: VPC Id
    Value:
      Ref: VPC
  NatGatewayIds:
    Description: Comma-delimited list of created NAT Gateway IDs
    Value:
      Fn::If:
        - HasAZ1
        - Ref: NatGateway
        - Ref: AWS::NoValue
